\ProvidesClass{documentation}
\LoadClass[11pt,leqno, twoside]{mwart}

\usepackage[polish]{babel}
\usepackage[margin=1.3in]{geometry}
\usepackage{polski}
\usepackage{fontspec}
\usepackage{caption}
\usepackage{url}
\defaultfontfeatures{Mapping=tex-text}
\frenchspacing

\renewcommand{\arraystretch}{1.5}
%\renewcommand{\labelitemi}{}
%\renewcommand{\labelitemii}{}
%\renewcommand{\labelitemiii}{}
%\renewcommand{\labelitemiv}{}

\usepackage{enumitem}
\setlist[itemize]{leftmargin=1cm}
